"use client";
import { useState } from "react";
const useCases=[
["Payments","Payment rule","AI or software asks to pay a vendor.","Parmana checks the vendor, amount and required approval.","If the request follows the rule, the payment can proceed. Otherwise it stops."],
["Refunds","Refund rule","AI or software asks to refund a customer.","Parmana checks the amount and the rule for that refund.","A refund outside the rule is stopped."],
["Access","Access rule","AI or software asks to give or change access.","Parmana checks who can give that access and what is allowed.","Allowed changes can proceed. Other changes stop."],
["Production changes","Change rule","AI or software asks to change a live system.","Parmana checks the change against the business's rules.","A change that meets the rules can proceed."],
["Data","Data rule","AI or software asks to delete records or stored data.","Parmana checks the rules that apply before anything is deleted.","Deletion happens only when the required conditions are met."],
["Software releases","Release rule","AI or software asks to release a code change.","Parmana checks the required reviews and release conditions.","A release that skips a required step is stopped."],
["Contracts","Signing rule","AI or software asks to accept terms or sign a contract.","Parmana checks who can commit the business and any limits.","A commitment outside those limits is stopped."],
["Vendors","Vendor rule","AI or software asks to add or buy from a vendor.","Parmana checks the business conditions that apply.","The action proceeds only when the required checks pass."]];
export default function UseCases(){const [active,setActive]=useState(0);const c=useCases[active];return <section id="use-cases" className="bg-lavender border-b border-border"><div className="max-w-container mx-auto px-6 py-16 md:py-20 lg:py-24"><h2 className="text-[26px] md:text-[36px] font-bold leading-[1.2] tracking-tight text-ink text-center max-w-[820px] mx-auto">Important actions should follow the business rules.</h2><p className="mt-3 text-base text-ink/70 text-center">If your business has a rule for an action, Parmana can check it before the action happens.</p><div className="mt-10 flex flex-wrap justify-center gap-3">{useCases.map((u,i)=><button key={u[0]} type="button" onClick={()=>setActive(i)} className={`rounded-md px-5 py-2 text-sm font-medium min-h-[44px] ${active===i?"bg-purple text-white":"border border-border bg-white text-ink/70"}`}>{u[0]}</button>)}</div><div className="mt-10 rounded-md border border-border bg-white p-8 md:p-10 max-w-[760px] mx-auto"><p className="text-xs uppercase tracking-wide font-mono text-purple-deep">{c[1]}</p><div className="mt-6 space-y-6"><div><p className="text-sm font-semibold text-ink">What is requested</p><p className="mt-2 text-sm leading-[1.65] text-ink/70">{c[2]}</p></div><div><p className="text-sm font-semibold text-ink">What Parmana checks</p><p className="mt-2 text-sm leading-[1.65] text-ink/70">{c[3]}</p></div><div className="pt-4 border-t border-border"><p className="text-sm font-semibold text-purple-deep">What happens</p><p className="mt-2 text-sm leading-[1.65] text-ink/70">{c[4]}</p></div></div></div></div></section>}
